import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import Modal from "./components/modals/Modal";
import { Nunito } from "next/font/google";
import Providers from "./components/provider";
import RegisterModal from "./components/modals/RegisterModal";
export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          {" "}
          <Navbar></Navbar>
          <RegisterModal></RegisterModal>
          {children}
        </Providers>
      </body>
    </html>
  );
}
