import Navbar from './components/navbar/Navbar'
import './globals.css'
import {Nunito} from "next/font/google"
export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"]
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar></Navbar>
        {children}</body>
    </html>
  )
}
